plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
}

android {
    namespace 're.manager.basket'
    compileSdk 34

    defaultConfig {
        applicationId "re.manager.basket"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}
